questions = {
    0:'make a dataframe from a list and a dictionary',
    1:'assign the columns, index, and data to varaibles and display',
    2:'display the dataframe\'s data types, value_counts, and info',
    3:'select the same column with loc and iloc, and then print out all types in the column',
    4:'return unique values from the column, and the frequencies of values in the column',
    5:'return the summary statistics of the column',
    6:'find the size and shape of the data',
    7:'check to see if there are missing values in the dataset',
    8:'rename index and column name',
    9:'create a column/delete a column',
    10:'sql: create a table and insert values',
    11:'sql: use like to select string match and/or/not',
    12:'create a vector and matrix in pytorch and numpy',
    13:'calculate the dot product of two vectors with pytorch',
    14:'multiple two matrices in pytorch',
    15:"create a function named mySum that takes n integers and returns their sum",
    16:"sql: total time spend by each employee: https://leetcode.com/problems/find-total-time-spent-by-each-employee/submissions/",
    17:"select integer columns from the dataframe, then select integers and objects",
    18:"reorder the column names by alphabetical order and reverse alpha order",
    19:"display the number of non-missing values in the columns",
    20:"make a file called foo.txt with two lines in the terminal and then add a third line",
    21:"ssh into @bandit.labs.overthewire.org with username bandit0, port 2220 and pw: bandit0",
    22:"search the terminal history for all instances of ssh",
    23:"create a binary tree node and class, add 7 nodes and print them in preorder traversal",
    24:"create two dataframes with similar keys and random data, do an inner join in both pandas and sql",
    25:"in the mode sql crunchbase database return value counts for each item in category code and order by highest to lowest",
    26:"in the mode sql crunchbase database return value counts for each item in category code and order by highest to lowest where the category begins with s or b",
    27:"select only the columns in the dataframe that are float64"
}